version: "3.9"
services:
  gallery:
    build:
      context: .
    image: c0ldcat/gallery:latest
    env_file: [.env.pass]
    ports:
      - 127.0.0.1:3012:80
    cap_add: [SYS_ADMIN]
    devices: 
      - /dev/fuse:/dev/fuse
    volumes:
      - $DCIM_PATH:/data:ro
      - data:/app/data
    init: true
    restart: unless-stopped
volumes:
  data:
