version: "3.9"
services:
  gallery:
    build:
      context: .
    image: c0ldcat/gallery:latest
    env_file: [.env.pass]
    environment:
      GALLERY_PATH: /mnt/gallery
    ports:
      - 127.0.0.1:3012:80
    cap_add: [SYS_ADMIN]
    devices: 
      - /dev/fuse:/dev/fuse
    volumes:
      - $GALLERY_PATH:/mnt/gallery:ro
      - data:/app/data
    init: true
    restart: unless-stopped
    network_mode: bridge
volumes:
  data:
