version: "3.9"
services:
  dcim-gallery:
    container_name: gallery
    build:
      context: .
    image: c0ldcat/gallery:latest
    env_file: [.env.pass]
    ports:
      - 0.0.0.0:3012:80
    cap_add: [SYS_ADMIN]
    devices: 
      - /dev/fuse:/dev/fuse
    volumes:
      - $DCIM_PATH:/data:ro